// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cepijdgyrvczjmtzjywj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcGlqZGd5cnZjemptdHpqeXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzIwNTEsImV4cCI6MjA2NDE0ODA1MX0.npUCE8MSFZLUo1pXJ2zIaE9ygLTJ6MV7cVaKqL-8U4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);